
FROM node:14-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install


COPY . .

RUN npm run build


FROM nginx:alpine


COPY --from=build /app/build /usr/share/nginx/html


EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]


# docker build -t front_react .
# docker run -p 8080:80 front_react

