FROM maven:3-jdk-11 as builder

WORKDIR /app

COPY /pom.xml .
RUN mvn dependency:go-offline


COPY /src ./src
RUN mvn clean package -DskipTests


FROM openjdk:11

WORKDIR /app


COPY --from=builder /app/target/*.jar .


ENTRYPOINT ["java", "-jar", "search-suggestion-service.jar"]

