FROM maven as builder

WORKDIR /app


COPY /pom.xml .
RUN mvn dependency:go-offline


COPY ./server/search-suggestion-service/src ./src
RUN mvn clean package -DskipTests


FROM openjdk

WORKDIR /app


COPY --from=builder /app/target/*.jar .

ENTRYPOINT ["java", "-jar", "*.jar"]
