FROM maven as builder

WORKDIR /app


COPY ./server/search-suggestion-service/pom.xml .
RUN mvn dependency:go-offline


COPY ./server/search-suggestion-service/src ./src
RUN mvn clean package -DskipTests


FROM openjdk

WORKDIR /app


COPY --from=builder /app/target/*.jar .

EXPOSE ${SEARCH_SUGGESTION_SERVICE_PORT}

# Exécution de l'application Spring Boot
ENTRYPOINT ["java", "-jar", "*.jar"]
