FROM maven as builder

WORKDIR /app


COPY /pom.xml .
RUN mvn dependency:go-offline


COPY /src ./src
RUN mvn clean package -DskipTests


FROM openjdk

WORKDIR /app


COPY --from=builder /app/target/.jar .


# Exécution de l'application Spring Boot
ENTRYPOINT ["java", "-jar", "search-suggestion-service-0.0.1-SNAPSHOT.jar"]
