FROM maven:3.6.0 as builder

WORKDIR /app


COPY /pom.xml .
RUN mvn dependency:go-offline


COPY /src ./src
RUN mvn clean package -DskipTests


FROM openjdk:11

WORKDIR /app


COPY --from=builder /app/target/*.jar .


# Exécution de l'application Spring Boot
ENTRYPOINT ["java", "-jar", "*.jar"]
