version: '3' 

services:
 
  # Database
  bdd:
    container_name: bdd
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:${AUTHENTICATION_SERVICE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - ecf
  #Server
  # Authentication service
  authentication-service:
    container_name: authen
    build: 
      context: ./server/authentication-service
      dockerfile: dockerfile
    ports:
      - "7001:${AUTHENTICATION_SERVICE_PORT}"  
    environment:
      PORT: ${AUTHENTICATION_SERVICE_PORT}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      DB_HOST: bdd
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - ecf

  # Common data service 
  common-data-service:
    build: 
      context: ./server/common-data-service
      dockerfile: dockerfile
    ports:
      - "808902:9000"
    depends_on:
      - bdd
    networks:
      - ecf

  # Payment service 
  payment-service:
    build: 
      context: ./
      dockerfile: server/payment-service/dockerfile
    ports:
      - "8083:9050"
    depends_on:
      - bdd
    networks:
      - ecf

   # front -end service
  client:
    build:
      #container_name: front
      context: ./client
      dockerfile: dockerfile
    
    ports:
      - 80:80
    depends_on:
      - authentication-service
    networks:
      - ecf

networks:
  mysqldb:
    driver: bridge

volumes:
  db_data:    

 
