FROM maven as builder
WORKDIR /app

COPY /pom.xml .
RUN mvn dependency:go-offline

COPY /src ./src
RUN mvn package -DskipTests

FROM openjdk

WORKDIR /app


COPY --from=builder app/target/*.jar .

ENTRYPOINT ["java", "-jar", "*.jar"]